-- MySQL Script generated by MySQL Workbench
-- 09/10/16 16:25:32
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`usuario` (
  `id` INT NULL AUTO_INCREMENT,
  `usuario` VARCHAR(16) NOT NULL,
  `senha` VARCHAR(200) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`sintegra`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`sintegra` (
  `id` INT NULL AUTO_INCREMENT,
  `cnpj` VARCHAR(25) NOT NULL,
  `resultado_json` LONGTEXT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`usuario_has_sintegra`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`usuario_has_sintegra` (
  `usuario_id` INT NOT NULL,
  `sintegra_id` INT NOT NULL,
  PRIMARY KEY (`usuario_id`, `sintegra_id`),
  INDEX `fk_usuario_has_sintegra_sintegra1_idx` (`sintegra_id` ASC),
  INDEX `fk_usuario_has_sintegra_usuario_idx` (`usuario_id` ASC),
  CONSTRAINT `fk_usuario_has_sintegra_usuario`
    FOREIGN KEY (`usuario_id`)
    REFERENCES `mydb`.`usuario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_usuario_has_sintegra_sintegra1`
    FOREIGN KEY (`sintegra_id`)
    REFERENCES `mydb`.`sintegra` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
