<div class="row">
    <h2 class="text-center">Search CNPJ</h2>
    <div class="col-xs-10">
        <div class="form-group">
            <input type="text" id="search" name="search" placeholder="cnpj" class="form-control">
        </div>
    </div>
    <div class="col-xs-2">
        <button class="btn btn-primary" onclick="search(document.getElementById('search').value.replace(/\D/g, ''))">Search</button>
    </div>
    <div id="result" class="col-xs-12"></div>
</div>