<?php
namespace Application;
use Zend\View\Renderer\PhpRenderer;
/** @var $this PhpRenderer */
?>

<table class="table table-striped">
    <thead>
        <tr>
            <th><strong>ID</strong></th>
            <th><strong>Json</strong></th>
            <th><strong>Option</strong></th>
        </tr>
    </thead>
    <?php
        foreach ($this->layout()->list as $item) {
            echo $item;
        }
    ?>
</table>